name: "Build Feature Test Package"
description: "Create a 2GP beta test package and store its id in a commit status"
inputs:
  cumulusci-version:
    description: 'version of CumulusCI to install'
    required: false
  sf-version:
    description: 'version of sf to install'
    required: false
  dev-hub-auth-url:
    description: 'sf auth URL for the Dev Hub'
    required: true
  org-name:
    description: 'Name of the scratch org config to use'
    required: true
    default: dev
  delete-scratch-org:
    type: string
    description: 'Specify whether to delete the Scratch org'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Build Feature Test Package
      if: ${{ (inputs.delete-scratch-org == 'true') }}
      uses: MyClubHub/cumulusci-run-flow-scratch@main
      with:
        dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
        org-name: '${{ inputs.org-name }}'
        cumulusci-version: '${{ inputs.cumulusci-version }}'
        sf-version: '${{ inputs.sf-version }}'
        flow-name: build_feature_test_package
        commit-status-name: "Build Feature Test Package"
        commit-status-regex: "04t[a-zA-Z0-9]*"
        commit-status-description-prefix: "version_id: "

    - name: Build Managed Test Package
      if: ${{ (inputs.delete-scratch-org == 'false') }}
      uses: MyClubHub/cumulusci-run-flow-scratch@main
      with:
        dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
        org-name: '${{ inputs.org-name }}'
        cumulusci-version: '${{ inputs.cumulusci-version }}'
        sf-version: '${{ inputs.sf-version }}'
        flow-name: create_managed_no_validation
        commit-status-name: "Build Feature Test Package"
        commit-status-regex: "04t[a-zA-Z0-9]*"
        commit-status-description-prefix: "version_id: "
        delete-scratch-org: '${{ inputs.delete-scratch-org }}'
